id: ICF8AFA7B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T17:54:08+00:00'
last_modified: '2022-06-08T06:49:51.574355+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20861
  title: ནེ་པཱལ་ལི་པི་པྲཀཤ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5BE4:
      image_group_id: I8LS20863
      title: ''
      total_pages: 158
      order: 1
      base_file: 5BE4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
